[tool.black]
line-length = 88
target-version = ['py311', 'py312']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | data
  | models
  | notebooks
)/
'''

[project]
name = "tech-challenge-ecommerce"
version = "0.1.0"
description = "Modelo preditivo para antecipação de NPS (Detrator) no e-commerce"
authors = [
    { name = "Roberto de Oliveira Junior", email = "r.oliveirajr@hotmail.com" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "scipy>=1.10.0",
    "scikit-learn>=1.2.0",
    "joblib>=1.2.0",
    "matplotlib>=3.7.0",
    "seaborn>=0.12.0"
]
